name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip if PR is in draft mode
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Auto-format and check
        run: |
          echo "🎨 Running Prettier auto-format..."
          npm run format
          echo "✅ Checking if formatting is correct..."
          npm run format:check

      - name: Unit Tests
        run: npm run test:coverage

      - name: Flag Validation Tests
        run: npm run test:flags

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage
